#+TITLE:     Working On: (already out of date...)
#+AUTHOR:    Cole Brown
#+EMAIL:     git@spydez.com
#+DATE:      [2019-03-05 Tue]

Next things?
  - To Do: [0/3]
    - [ ] configure-crypt needs babying... again... (again... (again?..))
    - [ ] remove references/?
      - Or put those files in repo... useless files now when not on whatever comp I downloaded em on.
      - ref files were for files that were/are very useful on their own and so preserving them for
        a decade or whatever from now would be useful.
        - Some of my old .emacs is just references to dead web links... not useful.
    - https://github.com/nhoffman/.emacs.d/blob/master/init.org
      - on: 22 http://nhoffman.github.io/.emacs.d/#orgbb1bc84
    - [ ] csetq vs setq all the places? see zeroth-funcs
      - csetq vs setq vs jamming everything into (use-package ... :custom ...)


Soon™ things?
  - To Do: [0/2]
    - [ ] make treemacs issue report?
    - [ ] make no-littering issue or fix w/ pull request?


Current things?
  - More things to do: [11/11]
    - [X] finish trawling zzazmboni config:
      - left off here: https://zzamboni.org/post/my-emacs-configuration-with-commentary/#literate-programming-using-org-babel
    - [X] https://emacs.stackexchange.com/questions/2427/how-to-test-rest-api-with-emacs
    - [X] More dates in org headers? Created, updated...
      - I think just "date" for now...?
    - [X] templates?
      - [X] for org headers?
      - [X] for blank .emacs.d config file?
    - [X] A more canonical place for the org file dates?
      - "#+DATE:" is actually used
    - [X] Notes/Issues
      - [X] configure-files-and-folders notes removed into its issue file notes
      - [X] epa/gpg notes into issues, for now?
    - [X] all-the-icons working enough for me now?
      - Uh... sure. And there's a todo or two up for the rest...
    - [X] file structure has changed...
    - [X] Also on bootstrap-debug-early todo
    - [X] update notes/*.org?
      - Think some todo'd placeholders have been done.
      - Still one todo but its full of temp tab links
    - [X] get yasnippets to load for org-mode, at least?
      my 'header' template doesn't work until you poke yasnippets a bit.


* A list of things to consider working on

  1) some sort of search for this .emacs.d project
     - [ ] Right now grep in projectile project doesn't like find command it generates.
       - Command works when pasted into (git for windows) bash, and emacs knows about bash...?
       - Command works in M-x shell.
       - Hm... Not sure right now.

  2) Projectile, use this .emacs.d project as test/tutorial?
     - working on it

  3) fuzzy stuff

  4) ...

  5) other note files...

  6) look into: https://www.reddit.com/r/emacs/comments/audffp/tip_how_to_use_a_stable_and_fast_environment_to/

  7) hi

* look at these:

https://www.reddit.com/r/emacs/comments/3kqt6e/2_easy_little_known_steps_to_speed_up_emacs_start/

https://www.emacswiki.org/emacs/OptimizingEmacsStartup
https://www.emacswiki.org/emacs/ProfileDotEmacs

* packages to consider

** Dashboard

(use-package dashboard
  :config
  (dashboard-setup-startup-hook))

https://www.reddit.com/r/emacs/comments/8jaflq/tip_how_to_use_your_dashboard_properly/

** Ace Jump Mode

Looks like it's Avy vs Ace Jump. Not sure if I want either. Avy seems newer?

https://www.emacswiki.org/emacs/AceJump
(use-package ace-jump-mode
  :bind
  ("C-c SPC" . ace-jump-mode))

$ find . -iname "*.el" -o -iname "*.org" | grep -v "/var/" | grep -v "/pre-no-littering/" | grep -v "/manual-package-archive/" | grep -v "/elpa/" | xargs grep "ace-jump"
./personal/docs/references/nhoffman.init.org:replacement for ace-jump-mode.
./personal/init/config/configure-hydra.el:    ;; Not using avy right now. Similar to ace-jump or easymotion.

** ediff

Do I need this with magit? Or at all?

(use-package ediff
  :config
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)
  (setq-default ediff-highlight-all-diffs 'nil)
  (setq ediff-diff-options "-w"))

https://www.gnu.org/software/emacs/manual/html_node/ediff/
https://www.emacswiki.org/emacs/EdiffMode
https://oremacs.com/2015/01/17/setting-up-ediff/
  - has reasons to use with magit

** helm search things

(use-package wgrep)

(use-package helm-ag)

(use-package helm-git-grep)

** page break line

https://github.com/purcell/page-break-lines

Don't think I see page breaks all that often/at all.
