#+TITLE:       Git Commands for Libs
#+AUTHOR:      Cole Brown
#+EMAIL:       git@spydez.com
#+DATE:        [2019-10-02 Wed]


* Setup the Upstream

** Configure a Remote

cole@cole-PC MINGW64 ~/.emacs.d/packages/submodules/org-roam (develop)
$ git remote -v
origin  git@github.com:cole-brown/org-roam.git (fetch)
origin  git@github.com:cole-brown/org-roam.git (push)

cole@cole-PC MINGW64 ~/.emacs.d/packages/submodules/org-roam (develop)
$ git remote add upstream https://github.com/jethrokuan/org-roam.git

cole@cole-PC MINGW64 ~/.emacs.d/packages/submodules/org-roam (develop)
$ git remote -v
origin  git@github.com:cole-brown/org-roam.git (fetch)
origin  git@github.com:cole-brown/org-roam.git (push)
upstream        https://github.com/jethrokuan/org-roam.git (fetch)
upstream        https://github.com/jethrokuan/org-roam.git (push)


* Updating These Libs

** org-roam:

!!!NOTE!!!
  - On 'develop' branch ATM.
  - git pull upstream develop

I chose 'git submodule' for this because:
  https://codewinsarguments.co/2016/05/01/git-submodules-vs-git-subtrees/
Initially chose subtree but may want to do bug fixes in a way I can pull-request back to owner.
  - my fork: git@github.com:cole-brown/org-roam.el.git
  - owner:   git@github.com:danielfm/org-roam.el.git

Run from git root directory (.emacs.d/):

Current Commands:

- Create/add:
    git submodule add git@github.com:cole-brown/org-roam.el.git packages/submodules/org-roam

  - Pull/update from (my) master:
    Like normal git.

  - Pull/update from upstream (my master's original repo, likely):
    Assumes 'upstream' is defined in submodule's config file.
    - optimistic
      git pull upstream master
    - pessimistic
      git co -b upstream_pull
      git pull upstream_pull


** spotify:

I chose 'git submodule' for this because:
  https://codewinsarguments.co/2016/05/01/git-submodules-vs-git-subtrees/
Initially chose subtree but may want to do bug fixes in a way I can pull-request back to owner.
  - my fork: git@github.com:cole-brown/spotify.el.git
  - owner:   git@github.com:danielfm/spotify.el.git

Run from git root directory (.emacs.d/):

Current Commands:

- Create/add:
    git submodule add git@github.com:cole-brown/spotify.el.git packages/submodules/spotify

  - Pull/update from (my) master:
    Like normal git.

  - Pull/update from upstream (my master's original repo, likely):
    Assumes 'upstream' is defined in submodule's config file.
    - optimistic
      git pull upstream master
    - pessimistic
      git co -b upstream_pull
      git pull upstream_pull
