#+TITLE:       Time In Modeline
#+AUTHOR:      Cole Brown
#+EMAIL:       git@spydez.com
#+DATE:        [2019-03-07 Thu]

display-time-mode took a lot of convincing to display a custom time.

Solution:
  - set display-time-string-forms to desired format
  - call display-time-update
    - Without this, emacs started with default, weird format until next minute or something.
  - set display-time-mode

Solution Code:
  (setq display-time-string-forms
        '((propertize (format-time-string "%F %H:%M" now)
                      'face 'bold))) ;; slightly bolded
  (display-time-update)
  (display-time-mode t)

See below for full code w/ comments. Or see config file.
  - [ ] TODO: figure out how to link to a source code file, ideally by comment or tag or something...

* Prereqs and Versions

None, really. display-time-mode is built in.

Versions:
  - Emacs for Windows installed
    - (emacs-version)
    - "GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30"

* Notes

Was trying to put a clock down in the mode line.

Wanted to set format to: yyyy-mm-dd HH:MM
Default has some weirdness. 
  e.g. the time "2019-03-07 22:45" would display as "2019-3- 7 22:45"

*** Easy way, wrong format:

For simple 24hr time:
;; (setq display-time-24hr-format t)
;; (display-time-mode t)

Worked, but not what I wanted.

*** Hard way:

Set format to: yyyy-mm-dd HH:MM
(trimmed down from: yy-mm-dd HH:MM:SS (Time Zone) <Mail notify>

Tried this, but wasn't working on restart of emacs - only when eval'd while debugging.

(setq display-time-string-forms
      ;; For 2 digit year: '((substring year -2) "/" month "/" day
      ;; Have to convert month/day to numbers, format back to strings in order to
      ;; make this not shitty (i.e. "2019-3- 6").
      '(year "-" (format "%02d" (string-to-number month)) "-" (format "%02d" (string-to-number day))
             " " 24-hours ":" minutes ; ":" seconds
             ;; Long-ass TZ: (if time-zone " (") time-zone (if time-zone ")")
             ;; Mail notice: (if mail " Mail" "")
             ))

Tried custom-set-variables, in case it was the same issue as the EPA/GPG fiasco, but same problem.

(custom-set-variables '(display-time-string-forms
      ;; For 2 digit year: '((substring year -2) "/" month "/" day
      ;; Have to convert month/day to numbers, format back to strings in order to
      ;; make this not shitty (i.e. "2019-3- 6").
      '(year "-" (format "%02d" (string-to-number month)) "-" (format "%02d" (string-to-number day))
             " " 24-hours ":" minutes ; ":" seconds
             ;; Long-ass TZ: (if time-zone " (") time-zone (if time-zone ")")
             ;; Mail notice: (if mail " Mail" "")
             )))

So `display-time-format', `display-time-day-and-date', and
`display-time-24hr-format' all seem to be useful and easier than
display-time-string-forms, but I couldn't convince them to behave.

(display-time-mode t)
(custom-save-all)


And then this finally worked:

For ISO time:
  https://emacs.stackexchange.com/questions/7365/how-to-display-date-in-julian-in-the-mode-line

Formatting:
  https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-Parsing.html

(setq display-time-string-forms
      '((propertize (format-time-string "%F %H:%M" now)
;;                    ))) ;; no change
;;                    'face 'mode-line-buffer-id))) ;; bold yellow/gold like buffer name
                    'face 'bold))) ;; slightly bolded
Faces to use to get into theme's customization from:
  https://www.gnu.org/software/emacs/manual/html_node/emacs/Standard-Faces.html
Propertize/format-time-string from:
  https://emacs.stackexchange.com/questions/13227/easy-way-to-give-the-time-its-own-face-in-modeline

;; Have to update, it seems, to get the reformat before a minute or so has passed?
(display-time-update)
(display-time-mode t)

* Archived Source Code/Notes

;;---
;; Time in the modeline
;;---
;; Puts a clock down in the mode line.

;; For simple 24hr time:
;; (setq display-time-24hr-format t)
;; (display-time-mode t)

;; For ISO time:
;; https://emacs.stackexchange.com/questions/7365/how-to-display-date-in-julian-in-the-mode-line
(require 'calendar)
;; Well, we're not full ISO 8601, but closeish.
;; Set format to: yyyy-mm-dd HH:MM
;; Formatting:
;;   https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-Parsing.html
(setq display-time-string-forms
      '((propertize (format-time-string "%F %H:%M" now)
;;                    ))) ;; no change
;;                    'face 'mode-line-buffer-id))) ;; bold yellow/gold like buffer name
                    'face 'bold))) ;; slightly bolded
;; Faces to use to get into theme's customization from:
;;   https://www.gnu.org/software/emacs/manual/html_node/emacs/Standard-Faces.html
;; Propertize/format-time-string from:
;;   https://emacs.stackexchange.com/questions/13227/easy-way-to-give-the-time-its-own-face-in-modeline

;; Have to update, it seems, to get the reformat before a minute or so has passed?
(display-time-update)
(display-time-mode t)

;; TODO: move stuff to a new issue.org
;; Set format to: yyyy-mm-dd HH:MM
;; (trimmed down from: yy-mm-dd HH:MM:SS (Time Zone) <Mail notify>
;; (setq display-time-string-forms
;;       ;; For 2 digit year: '((substring year -2) "/" month "/" day
;;       ;; Have to convert month/day to numbers, format back to strings in order to
;;       ;; make this not shitty (i.e. "2019-3- 6").
;;       '(year "-" (format "%02d" (string-to-number month)) "-" (format "%02d" (string-to-number day))
;;              " " 24-hours ":" minutes ; ":" seconds
;;              ;; Long-ass TZ: (if time-zone " (") time-zone (if time-zone ")")
;;              ;; Mail notice: (if mail " Mail" "")
;;              ))
;; (custom-set-variables '(display-time-string-forms
;;       ;; For 2 digit year: '((substring year -2) "/" month "/" day
;;       ;; Have to convert month/day to numbers, format back to strings in order to
;;       ;; make this not shitty (i.e. "2019-3- 6").
;;       '(year "-" (format "%02d" (string-to-number month)) "-" (format "%02d" (string-to-number day))
;;              " " 24-hours ":" minutes ; ":" seconds
;;              ;; Long-ass TZ: (if time-zone " (") time-zone (if time-zone ")")
;;              ;; Mail notice: (if mail " Mail" "")
;;              )))
;; So `display-time-format', `display-time-day-and-date', and
;; `display-time-24hr-format' all seem to be useful and easier than
;; display-time-string-forms, but I couldn't convince them to behave.
;;(display-time-update)
;;(display-time-mode t)
;;(custom-save-all)
