#+TITLE:     File Structure of .emacs.d
#+AUTHOR:    Cole Brown
#+EMAIL:     git@spydez.com
#+DATE:      [2019-03-06 Wed]

TODO: update this with latest dir tree.

* Linux / directory structure
  /bin
    - (essential) binaries
    - less essential binaries stored in e.g. /usr/bin
    - /sbin is system admin binaries
  /boot
    - just bootloader and other boot stuff
  /dev
    - devices
      - /dev/sda for serial drive a
      - /dev/random for RNG, etc
  /etc
    - config files
      - Cuz nothing says "config" like "etc"... /s
  /home
    - user home folders
  /lib
    - (essential) (shared) libraries
  /lost+found
    - file system crash stuff
  /media
    - removable media
      - CDs, USBs etc.
  /mnt
    - (temp) mount points
  /opt
    - ...optional packages?
    - proprietary stuff that doesn't want to use the linux dir hirearchy
  /proc
    - special files for system/process info
  /root
    - user dir of root user
  /run
    - temp/transient app state files
  /sbin
    - sys admin binaries, see /bin
  /selinux
    - SELinux special files
  /srv
    - "data for services provided by the system"
  /tmp
    - ...more temp files for apps?
  /usr
    - user binaries and read-only data
      - for apps run by the users, as opposed to run by the system
    - /usr/bin, /usr/sbin, /usr/lib, /usr/local, ....
  /var
    - variable data files
    - "writable counterpart to the /usr dir"

* My emacs personal directory

TODO: defaults, domains, computers... change folders to be together in browser/dir list?
  - e.g. _defaults, _domains, _computers?
  - notes dir? "notes", "zzz_notes" Or keep notes in with code?
    - works sometimes, but e.g. gpg debug/notes/rant got real long and doesn't apply much to final code?

Right now:
 .emacs.d/
   spydez/
     computers/
     defaults/
     domains/
     lisp/
     references/
     snippets/
     use-tool/
     (init files loose in spydez/)

These are:
  - init stuff
  - notes/refs
  - my lisp funcs/baby proto-packages
  - my emacs stuff for other emacs packages (snippets)

Adjust folder tree?
 .emacs.d/
   spydez/
     init/{computers, defaults, domains... loose files?}
     var/etc/whatever? with rest of stuff? idk

 OR...
 .emacs.d/
   init/{computers, defaults, domains... loose files?}
   personal/{my (non-init) stuff?}
   var?/a place for other stuff?

.emacs.d/
  var/     no-littering puts stuff here
  etc/     no-littering puts stuff here
  {spydez|personal}/
    {dev|setup|config}/
      computers,defaults,domains/?
    {docs}/
      notes,references/?
    lisp/
    use-tool/
    init/?
      boot/?
        bootstrap-*
      config/?
        config-*
      finalize/?
        finalize-*


.emacs.d/
  var/     no-littering puts stuff here
  etc/     no-littering puts stuff here
  {spydez|personal}/
    {dev|setup|config}/
      computers,defaults,domains/?
    {docs}/
      notes,references/?
    lisp/
    use-tool/
    init/?
      0_zero/?
        early-init stuff?
      boot/?
        bootstrap-*
      config/?
        config-*
      finalize/?
        finalize-*

.emacs.d/ [2019-03-07]
  elpa/    - packages
  etc/     - no-littering puts stuff here
  var/     - no-littering puts stuff here
  server/  - emacs server file
  LICENSE  - license
  early-init.el - emacs: early init
  init.el       - emacs: regular init
  manual-package-archive/ - ye olde non-elpa packages
  personal/ - all my other emacs stuff
    dev/    - devices
      computers/ - individual computer setup/overrides
      defaults/  - defaults for individuals/domains
      domains/   - domain (home, work) level setup/overrides
    docs/ - non-code files
      issues/ - errors, bugs, and annoyances encountered
      notes/  - notes and stuff like this
      references/ - I don't trust the internet to keep these around until I need them again.
    lisp/ - my non-init emacs-lisp code
    snippets/ - my yasnippet collection
    use-tool/ - my first, feeble, half-hearted attempt at making something to track exo-emacs applications.
    init/ - initialization
      zeroth/   - pre-boot stuff - early-init stuff
      boot/     - post-early-init but pre-package configuration
      config/   - setting up emacs, enabling and setting up packages, etc.
      finalize/ - double checking, sanity checks...

* Reorg in progress

  - .emacs.d/ [12/14]
    - var/     no-littering puts stuff here
    - etc/     no-littering puts stuff here
    - [X] {spydez|personal}/?
      - personal.
    - personal/lisp/
    - personal/use-tool/
    - [X]   {docs}/
    - [X]     notes,references/?
      - Yep.
    - [X]   {dev|setup|config}/
      - dev.
    - [X]     computers,defaults,domains/?
      - yep.
    - [X]   init/?
    - [ ]     0_zero/? zeroth/?
    - [ ]       early-init stuff?
    - [X]     boot/?
    - [X]       bootstrap-*
    - [X]     config/?
    - [X]       config-*
    - [X]     finalize/?
    - [X]       finalize-*

* TODOs

search for: TODO-reorg-done
