#+TITLE:     Links: Interesting or Maybe Useful
#+AUTHOR:    Cole Brown
#+EMAIL:     git@spydez.com
#+DATE:      [2019-03-03 Sun]

* Learning
[2019-03-15]

** Rust / Operating System

a teaching OS written in Rust

https://os.phil-opp.com/

** Git / (...Rust maybe?)

"Write yourself a Git!" blog post. Could maybe do it in Rust or Go instead of Python...
https://wyag.thb.lt/
https://news.ycombinator.com/item?id=19386141

* Sys Admin
[2019-03-04]

Giant list of open-source sysadmin software/resources.
https://github.com/kahun/awesome-sysadmin

*** [[https://en.wikipedia.org/wiki/System_administrator][wikipedia]]

Mainly for some nice search target keywords...

A system administrator, or sysadmin, is a person who is responsible for the upkeep, configuration, and reliable operation of computer systems; especially multi-user computers, such as servers. The system administrator seeks to ensure that the uptime, performance, resources, and security of the computers they manage meet the needs of the users, without exceeding a set budget when doing so.

To meet these needs, a system administrator may acquire, install, or upgrade computer components and software; provide routine automation; maintain security policies; troubleshoot; train or supervise staff; or offer technical support for projects.
